#!/usr/bin/env python3
"""Hybrid quantum-classical planner trainer (Quantum Learning Loop exercise).

Trains a 2-qubit variational circuit that maps an agent's 2D need vector to a
preference score for action 0 (action 1 = 1 - score). Trained scores are
exported to quantum/scores.json so the live browser sim uses them as the
QUANTUM layer of a hybrid planner (blended with a classical utility baseline).

Simulator-only (PennyLane default.qubit). No real QPU.
Run: python quantum/quantum_planner.py
"""
import json
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "scores.json")


def main():
    try:
        import pennylane as qml
    except ImportError:
        print("pennylane not installed; run: pip install pennylane numpy")
        return 1

    dev = qml.device("default.qubit", wires=2)

    # qml.numpy so weights are differentiable for the optimizer
    npq = qml.numpy

    def circuit(weights, x):
        qml.RX(x[0] * npq.pi, wires=0)
        qml.RY(x[1] * npq.pi, wires=1)
        qml.CNOT(wires=[0, 1])
        qml.Rot(*weights[0], wires=0)
        qml.Rot(*weights[1], wires=1)
        qml.CNOT(wires=[0, 1])
        return qml.expval(qml.PauliZ(0))

    @qml.qnode(dev)
    def qnode(weights, x):
        return circuit(weights, x)

    rng = np.random.default_rng(0)
    weights = npq.array(rng.normal(scale=0.1, size=(2, 3)), requires_grad=True)

    # toy training data: need0 high -> action0 wins; need1 high -> action1 wins
    X = np.array([[1.0, 0.0], [0.9, 0.1], [0.0, 1.0], [0.1, 0.9],
                  [0.5, 0.5], [0.8, 0.2], [0.2, 0.8], [0.0, 0.0]], float)
    Y = np.array([1.0, 0.9, 0.0, 0.1, 0.5, 0.75, 0.25, 0.5])  # action0 pref

    # robust manual SGD via qml.grad (version-proof)
    def loss(w):
        total = 0.0
        for x, y in zip(X, Y):
            pred = (qnode(w, x) + 1) / 2
            total = total + (pred - y) ** 2
        return total / len(X)
    grad_fn = qml.grad(loss)
    lr = 0.08
    for _ in range(200):
        g = grad_fn(weights)
        weights = weights - lr * g

    grid, scores = [], []
    for n0 in np.linspace(0, 1, 11):
        for n1 in np.linspace(0, 1, 11):
            s0 = (qnode(weights, np.array([n0, n1])) + 1) / 2
            grid.append([round(float(n0), 3), round(float(n1), 3)])
            scores.append([round(float(s0), 4), round(float(1 - s0), 4)])

    with open(OUT, "w") as f:
        json.dump({"states": grid, "scores": scores,
                   "note": "VQC action0 preference for 2D need vector"}, f)
    # browser-loadable copy (no fetch/CORS) for agent_vision.html
    js_path = os.path.join(HERE, "scores.js")
    with open(js_path, "w") as f:
        f.write("// AUTO-GENERATED by quantum/quantum_planner.py — do not edit.\n")
        f.write("window.QIG_QUANTUM = ")
        json.dump({"states": grid, "scores": scores}, f)
        f.write(";\n")
    print(f"wrote {OUT} ({len(grid)} states) + {js_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
