#!/usr/bin/env python3
"""Hybrid quantum-classical planner trainer (Quantum Learning Loop exercise).

Trains a 2-qubit variational circuit that maps an agent's 2D need vector
[hunger, rest] to a 3-output action preference [seek_food, wander, rest].
Trained scores are exported to quantum/scores.json so the live browser sim uses
them as the QUANTUM layer of a hybrid planner (blended with a classical utility
baseline at 0.6 classical + 0.4 quantum).

Targets encode a sensible survival policy:
  - high hunger, low rest  -> seek_food
  - low hunger, high rest  -> rest
  - otherwise              -> wander (pursue vocation)

Simulator-only (PennyLane default.qubit). No real QPU.
Run: python quantum/quantum_planner.py
"""
import json
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "scores.json")


def main():
    try:
        import pennylane as qml
    except ImportError:
        print("pennylane not installed; run: pip install pennylane numpy")
        return 1

    dev = qml.device("default.qubit", wires=2)
    npq = qml.numpy

    def circuit(weights, x):
        # encode both need dimensions
        qml.RX(x[0] * npq.pi, wires=0)
        qml.RY(x[1] * npq.pi, wires=1)
        qml.CNOT(wires=[0, 1])
        qml.Rot(*weights[0], wires=0)
        qml.Rot(*weights[1], wires=1)
        qml.CNOT(wires=[0, 1])
        # 3 observables -> 3 action-preference outputs
        return (qml.expval(qml.PauliZ(0)),
                qml.expval(qml.PauliZ(1)),
                qml.expval(qml.Hadamard(0) @ qml.Hadamard(1)))

    @qml.qnode(dev)
    def qnode(weights, x):
        return circuit(weights, x)

    rng = np.random.default_rng(0)
    weights = npq.array(rng.normal(scale=0.1, size=(2, 3)), requires_grad=True)

    # 2D grid training data: [hunger, rest] -> prefer [seek_food, wander, rest]
    X, Y = [], []
    for h in np.linspace(0, 1, 6):
        for r in np.linspace(0, 1, 6):
            X.append([float(h), float(r)])
            if h > 0.6 and r < 0.6:
                Y.append([1.0, 0.0, 0.0])      # hungry -> seek food
            elif r > 0.6 and h < 0.6:
                Y.append([0.0, 0.1, 1.0])      # tired -> rest
            elif h > 0.6 and r > 0.6:
                Y.append([0.8, 0.0, 0.6])      # both high -> food slightly favored
            else:
                Y.append([0.1, 1.0, 0.0])      # calm -> wander / vocation
    X = np.array(X, float)
    Y = np.array(Y, float)

    def loss(w):
        total = 0.0
        for x, y in zip(X, Y):
            pred = (npq.array(qnode(w, x)) + 1) / 2  # map [-1,1] -> [0,1]
            total = total + npq.sum((pred - y) ** 2)
        return total / len(X)

    grad_fn = qml.grad(loss)
    lr = 0.08
    for _ in range(200):
        g = grad_fn(weights)
        weights = weights - lr * g

    # export a 11x11 grid of (hunger, rest) -> [seek_food, wander, rest]
    grid, scores = [], []
    for n0 in np.linspace(0, 1, 11):
        for n1 in np.linspace(0, 1, 11):
            p = (npq.array(qnode(weights, np.array([n0, n1]))) + 1) / 2
            grid.append([round(float(n0), 3), round(float(n1), 3)])
            scores.append([round(float(p[0]), 4),
                           round(float(p[1]), 4),
                           round(float(p[2]), 4)])

    with open(OUT, "w") as f:
        json.dump({"states": grid, "scores": scores,
                   "note": "VQC 2D need [hunger,rest] -> 3-action pref [seek_food,wander,rest]"}, f)
    # browser-loadable copy (no fetch/CORS) for agent_vision.html
    js_path = os.path.join(HERE, "scores.js")
    with open(js_path, "w") as f:
        f.write("// AUTO-GENERATED by quantum/quantum_planner.py — do not edit.\n")
        f.write("window.QIG_QUANTUM = ")
        json.dump({"states": grid, "scores": scores}, f)
        f.write(";\n")
    print(f"wrote {OUT} ({len(grid)} states) + {js_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
